name: GitHub Follower Bot Running

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  up-and-running:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run Follower bot
        run: |
          export github_user=oxoovo
          export personal_github_token=${{ secrets.PERSONAL_GITHUB_TOKEN }}
          pipenv run python follower_bot.py
      - name: Commit and push if it changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update Followerd"
          git push origin master
